/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package mn.dulmandakh.reactnative.extensions

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
